### ISSUE TITLE
Add proper tests

### ISSUE THREAD

**Issue by sloede** [trixi-framework/HOHQMesh.jl#3]
Right now, we only use a crude smoke test. We should at least properly verify the mesh generation for a non-trivial 2D and a non-trivial 3D example.

**Comment by andrewwinters5000** [comment]
We partially do this now in that a single element in a 2D mesh (via AbaqusReader) is checked against known reference values. I could add a 3D variant of this test as well. Would that be enough to address this issue?

**Comment by sloede** [comment]
I believe so. This would at least fail if anything major in the toolchain breaks down. A 3D variant would be useful as well, then this can be closed I believe.

**Comment by andrewwinters5000** [comment]
Done. I added a 3D test (among others) in #15
