### ISSUE TITLE
Tutorial in the docs seems outdated

### ISSUE THREAD

**Issue by jlchan** [trixi-framework/HOHQMesh.jl#30]
https://trixi-framework.github.io/HOHQMesh.jl/dev/guided-tour/#Build-a-mesh-from-scratch

In particular, `saveProject` does not run automatically when `generate_mesh` is called, and `saveProject(p, ::String)` doesn't seem to work (only a `saveProject(p)` signature appears to be exported). This is with v0.2.1 on @marklopat's Windows machine.

**Comment by DavidAKopriva** [comment]
There is no `saveProject(p, ::String)` method, so that should be fixed. However, saveProject is called when generate_mesh is invoked at L31. (If it wasn't, then HOHQMesh.f90 wouldn't have a control file to generate a mesh.) So I am asking for more details here as to why you don't think it is.

**Comment by jlchan** [comment]
When we tried it again yesterday, @MarkLopat was copying and pasting the code into the REPL. For some reason, the last two commands were getting transformed into strings and not being run. I don't think this issue is related to HOHQMesh or HOHQMesh.jl, though.

**Comment by andrewwinters5000** [comment]
I will update the docs in a forthcoming PR to address this issue. I found that the "Guided tour" (and possibly other places) indicates the wrong call signature for the `saveProject` function as shown in this screenshot from the current docs (the last part of the "Guided tour" page):

<img width="838" alt="Screenshot 2024-01-05 at 07 20 38" src="https://github.com/trixi-framework/HOHQMesh.jl/assets/25242486/63bf9488-43d2-4eeb-91ae-52fbd6b4e017">
