### ISSUE TITLE
Deprecation warning from Makie.jl for `resolution` keyword

### ISSUE THREAD

**Issue by sloede** [trixi-framework/HOHQMesh.jl#54]
When I try to generate a mesh using the great wavy walls example by @andrewwinters5000, which I adapted in https://github.com/trixi-framework/talk-2024-dlr-braunschweig-trends-dgsem/blob/f57927e5acce89c8c26ac0dd7444725e00e39e92/examples/generate_mesh_cylinder_with_sine_walls.jl, I get the following deprecation warning from Makie.jl:
```
┌ Warning: Found `resolution` in the theme when creating a `Scene`. The `resolution` keyword for `Scene`s and `Figure`s has been deprecated. Use `Figure(; size = ...` or `Scene(; size = ...)` instead, which better reflects that this is a unitless size and not a pixel resolution. The key could also come from `set_theme!` calls or related theming functions.
└ @ Makie ~/.julia/packages/Makie/VRavR/src/scenes.jl:220
```
Any idea what's wrong here and how to fix it?

**Comment by andrewwinters5000** [comment]
I am not sure why it would still throw this warning because I removed all these deprecated keywords in c7f497fba157d35ab1d143d1a9df45306fdeae1d. Are you using the latest version of HOHQMesh.jl?

**Comment by sloede** [comment]
No, and I apologize for the overhead I caused 🤦. Thanks for the feedback!
